service: serverless-dynamodb
disabledDeprecations:
  - "*"
configValidationMode: off
frameworkVersion: ^3.39.0

useDotenv: true

provider:
  name: aws
  region: 'us-east-1'
  stage: ${opt:stage, 'local'}
  runtime: nodejs20.x
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: '*'
  environment:
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    TABLE_NAME: ${env:TABLE_NAME}
plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline
package:
  individually: true
custom:
  esbuild:
    config: ./esbuild.config.js
  serverless-offline: ${file(config/custom.yaml):SERVERLESS_OFFLINE}
  serverless-dynamodb: ${file(config/dynamodb.yaml)}      
resources:
  - ${file(config/resources.yaml)}    
functions:
  - ${file(src/users/routes.yaml)}
  - ${file(src/post/routes.yaml)}
  - ${file(src/comment/routes.yaml)}