functions:
  comments-by-post:
    name: comments-by-post
    handler: src/comment/infrastructure/handlers/main.postComments
    description: Get all comments of a post
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/posts/{postId}/comments
          cors: true
          # authorizer: jwtAuthorizer

  comments-get-by-id:
    name: comments-get-by-id
    handler: src/comment/infrastructure/handlers/main.findOne
    description: Get a comment by id
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/comments/{commentId}
          cors: true
          # authorizer: jwtAuthorizer

  comments-by-user:
    name: comments-by-user
    handler: src/comment/infrastructure/handlers/main.userComments
    description: Get all comments of a user
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/users/{userId}/comments
          cors: true
          # authorizer: jwtAuthorizer

  comments-create:
    name: comments-create
    handler: src/comment/infrastructure/handlers/main.create
    description: Create a comment under a post
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: post
          path: /api/v1/posts/{postId}/comments
          cors: true
          # authorizer: jwtAuthorizer

  comment-likes-create:
    name: comment-likes-create
    handler: src/comment/infrastructure/handlers/main.commentLiked
    description: Like a comment (idempotent)
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: post
          path: /api/v1/comments/{commentId}/likes
          cors: true
          # authorizer: jwtAuthorizer

  comment-likes-delete:
    name: comment-likes-delete
    handler: src/comment/infrastructure/handlers/main.deleteCommentLike
    description: Remove like from a comment
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: delete
          path: /api/v1/comments/{commentId}/likes
          cors: true
          # authorizer: jwtAuthorizer
