functions:
  posts-get-all:
    name: posts-get-all
    handler: src/post/infrastructure/handlers/main.findAll
    description: Get all posts
    # reservedConcurrency: 1   # ⚠️ Quitar salvo que necesites serializar
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/posts
          cors: true
          # authorizer: jwtAuthorizer   # ← define en 'provider.httpApi.authorizers'

  posts-get-by-id:
    name: posts-get-by-id
    handler: src/post/infrastructure/handlers/main.findOne
    description: Get a post by id
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/posts/{id}
          cors: true
          # authorizer: jwtAuthorizer

  users-get-posts:
    name: users-get-posts
    handler: src/post/infrastructure/handlers/main.userPost
    description: Get all posts for a user
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/users/{userId}/posts
          cors: true
          # authorizer: jwtAuthorizer

  posts-create:
    name: posts-create
    handler: src/post/infrastructure/handlers/main.create
    description: Create a post
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: post
          path: /api/v1/posts
          cors: true
          # authorizer: jwtAuthorizer

  posts-like-create:
    name: posts-like-create
    handler: src/post/infrastructure/handlers/main.postLiked
    description: Create a like on a post (idempotent)
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: post
          path: /api/v1/posts/{id}/likes
          cors: true
          # authorizer: jwtAuthorizer
