  user-get-all:
    name: user-get-all
    handler: src/users/infrastructure/handler/main.findAll
    description: get all users
    reservedConcurrency: 1
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          path: api/v1/users
          method: get
  user-get:
    name: user-get
    handler: src/users/infrastructure/handler/main.findOne
    description: get a user
    reservedConcurrency: 1
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          path: api/v1/users/{id}
          method: get          
  user-post:
    name: user-create
    handler: src/users/infrastructure/handler/main.create
    description: create a user
    reservedConcurrency: 1
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          path: api/v1/users
          method: post
