functions:
  users-get-all:
    name: users-get-all
    handler: src/users/infrastructure/handler/main.findAll
    description: List users (paginated, filtered)
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/users
          cors: true
          # authorizer: jwtAuthorizer   # define en provider.httpApi.authorizers

  users-get-by-id:
    name: users-get-by-id
    handler: src/users/infrastructure/handler/main.findOne
    description: Get user by id
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: get
          path: /api/v1/users/{userId}
          cors: true
          # authorizer: jwtAuthorizer

  users-create:
    name: users-create
    handler: src/users/infrastructure/handler/main.create
    description: Create user (idempotent)
    memorySize: 256
    timeout: 10
    environment:
      TOTAL: ${env:TOTAL}
    events:
      - httpApi:
          method: post
          path: /api/v1/users
          cors: true
          # authorizer: jwtAuthorizer
